name: raundtable
description: RaundTable MVP.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # firebase | google
  cloud_firestore: ^3.1.10
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  firebase_storage: ^10.2.9
  firebase_messaging: ^11.2.8
  google_sign_in: ^5.2.4

  # icons
  cupertino_icons: ^1.0.2

  # forms
  flutter_form_builder: '7.1.1'
  form_builder_validators: ^7.7.0
  phone_number: ^0.12.0+1
  country_pickers: ^2.0.0
  flutter_typeahead: ^3.2.4

  # utilities
  flutter_switch: ^0.3.2
  styled_widget:
  custom_navigation_bar: ^0.8.2
  freezed_annotation: ^1.1.0
  google_fonts: ^2.3.1
  pin_code_fields: ^7.3.0
  relative_scale: ^2.0.0
  timer_button:
    git:
      url: https://github.com/AndresPlanit/timer_button.git
      ref: patch-1
  form_validator: ^1.0.2
  intl_phone_field: ^3.0.1
  intl_phone_number_input: ^0.7.0+2
  contacts_service: ^0.6.3
  percent_indicator: ^3.4.0
  im_stepper: ^0.1.3

  modal_bottom_sheet: ^2.0.1
  flutter_advanced_avatar: ^1.0.0+1
  form_field_validator: ^1.1.0
  permission_handler: ^9.2.0

  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.1.10
  flutter_lints: ^1.0.0
  change_app_package_name: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/logo_white.jpg
    - lib/features/dashboard/pic.jpeg
    - assets/images/
