// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIviBYSgAqQMCwIR5JNprcy5JkWQMNPGs',
    appId: '1:1048016560161:web:54cbfa16bc7cb22c22c360',
    messagingSenderId: '1048016560161',
    projectId: 'raundtable-624e5',
    authDomain: 'raundtable-624e5.firebaseapp.com',
    storageBucket: 'raundtable-624e5.appspot.com',
    measurementId: 'G-Y1J1KYPYN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUtdFynrG8YfXs72voKVsznf6XDfjZvIk',
    appId: '1:1048016560161:android:3a900d990556a8ef22c360',
    messagingSenderId: '1048016560161',
    projectId: 'raundtable-624e5',
    storageBucket: 'raundtable-624e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwgNXypwZgG89J_xcz7-iM5E33Evn2ZyU',
    appId: '1:1048016560161:ios:8f9d3b46331fd2ba22c360',
    messagingSenderId: '1048016560161',
    projectId: 'raundtable-624e5',
    storageBucket: 'raundtable-624e5.appspot.com',
    iosClientId: '1048016560161-oiu3iif5ifucnn3b2a0dla4erepj55e9.apps.googleusercontent.com',
    iosBundleId: 'com.raundtable.raundtable',
  );
}
